#spring.datasource.url: jdbc:h2:mem:testdb
#spring.datasource.url: jdbc:h2:file:C:\Users\Romerro\IdeaProjects\springdeliverydelay\target\testDB;AUTO_SERVER=TRUE
#spring.datasource.driverClassName: org.h2.Driver
#spring.datasource.username: sa
#spring.datasource.password: ""


spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
spring.datasource.driverClassName: org.postgresql.Driver
spring.datasource.username: postgres
spring.datasource.password: 123